/**
 * Media source adapter contract. D-01 §6.4.
 *
 * ADR-002 / TD-002: yt-dlp is GPLv3+. The ADR says it must be "architecturally
 * replaceable", and `oss-scout` correctly pointed out that a comment saying so is not a
 * guarantee. This interface is the guarantee: `YtDlpSource` is one registry entry among
 * several, and the registry keeps working when it is removed.
 *
 * The proof is not this comment either — it is
 * `media/__tests__/ytdlpRemoval.test.ts`, which disables the adapter and asserts
 * the product still resolves podcasts, RSS, HLS and direct links.
 *
 * TYPE OWNERSHIP (ADR-001 mandate 2): `MediaInfo` and `FetchedMedia` are OUR types.
 * yt-dlp's JSON has hundreds of unstable fields; none of them may leak past the adapter
 * boundary into business code.
 */

export type MediaSourceId = 'local-file' | 'direct-http' | 'rss' | 'yt-dlp';

export interface MediaTrack {
  /** Our own id, not the upstream format id. */
  id: string;
  kind: 'audio' | 'video' | 'muxed';
  codec: string | null;
  bitrateKbps: number | null;
  sampleRateHz: number | null;
  channels: number | null;
  sizeBytes: number | null;
}

export interface MediaInfo {
  /** Stable identity for dedup; a content hash where we have one, else the normalised URL. */
  sourceKey: string;
  title: string | null;
  durationMs: number | null;
  /** Never rendered as HTML; the UI treats it as plain text. */
  description: string | null;
  thumbnailUrl: string | null;
  uploader: string | null;
  publishedAt: string | null;
  tracks: MediaTrack[];
  /** True when this input expands into several items (an RSS feed, a playlist). */
  isCollection: boolean;
  /** For collections: the child inputs, to be enqueued as separate jobs. */
  children?: { input: string; title: string | null }[];
  /** Which adapter produced this. Recorded so the UI can show provenance. */
  producedBy: MediaSourceId;
}

export interface FetchedMedia {
  /** Absolute path to the downloaded file, inside the managed temp dir. */
  path: string;
  sizeBytes: number;
  /** Content type as observed, not as claimed by the user. */
  contentType: string | null;
  /** True when the file contains only audio (no re-mux needed downstream). */
  audioOnly: boolean;
  producedBy: MediaSourceId;
}

export interface FetchRequest {
  input: string;
  /** Managed destination directory. The adapter never chooses its own path. */
  destDir: string;
  /** Basename WITHOUT extension, generated by us (never user-supplied). D-01 §8.5. */
  destBasename: string;
  preferAudioOnly: boolean;
  maxBytes: number;
  signal: AbortSignal;
  onProgress?: (fraction: number) => void;
}

export type Availability = { ok: true } | { ok: false; reason: string; remediation: string };

export interface MediaSource {
  readonly id: MediaSourceId;
  readonly kind: 'media-source';
  /** SPDX identifier. Surfaced in the UI so the licence story stays visible. */
  readonly license: string;

  /**
   * 0 = will not handle this input. Higher wins.
   *
   * D-01 §6.4: YtDlpSource must return the LOWEST positive score so it is only ever the
   * fallback. That ordering is what makes "we do not depend on a GPL component by
   * default" true in code rather than in prose.
   */
  match(input: string): number;

  isAvailable(): Promise<Availability>;

  probe(input: string, signal: AbortSignal): Promise<MediaInfo>;

  fetch(req: FetchRequest): Promise<FetchedMedia>;
}

/** Thrown when no enabled adapter can handle an input. Carries actionable remediation. */
export class NoMediaSourceError extends Error {
  constructor(
    readonly input: string,
    readonly remediation: string,
  ) {
    super(`no media source can handle this input`);
    this.name = 'NoMediaSourceError';
  }
}
