/**
 * Model registry schema.
 *
 * Baseline: memo.ac's shipped registries (ADR-004 decision 4), plus our three additions
 * and one removal. See artifacts.ts for the full provenance note.
 */

import type {
  ArtifactFile,
  BenchmarkResult,
  GgufMetadata,
  LicenseInfo,
  ProviderId,
  ReferenceBenchmark,
  ResourceRequirements,
} from './artifacts.js';

/**
 * What the model is for. Drives which "active model" slot it can occupy.
 *
 * Matches D-02 `model_installs.role` CHECK exactly — VAD and punctuation models are NOT
 * ASR models, and filing them under 'asr' would put a VAD net in the transcription slot.
 */
export const MODEL_ROLES = [
  'asr',
  'llm',
  'vad',
  'punctuation',
  'diarization',
  'embedding',
  'tts',
] as const;
export type ModelRole = (typeof MODEL_ROLES)[number];

export const MODEL_FORMATS = ['ggml', 'gguf', 'onnx', 'nemo', 'coreml'] as const;
export type ModelFormat = (typeof MODEL_FORMATS)[number];

/**
 * Quantization level. ADR-004 gap ① — memo.ac has no quantization concept at all
 * (every Whisper model it ships is f16), which is why its Whisper large-v3 is a
 * 3.09 GB download where ours is 1.08 GB at q5_0.
 *
 * `f16`/`f32` are "no quantization" sentinels rather than a null, so the UI always
 * has something concrete to show in the quantization selector.
 */
export const QUANTIZATIONS = [
  'f32', 'f16', 'bf16',
  'q8_0', 'q6_k', 'q5_k_m', 'q5_1', 'q5_0', 'q4_k_m', 'q4_k_s', 'q4_0',
  'q3_k_m', 'q2_k', 'iq4_xs', 'iq3_m', 'iq2_m',
] as const;
export type Quantization = (typeof QUANTIZATIONS)[number];

/** Human-facing grouping for the quantization selector (borrowed from Jan's Small/Balanced/Large). */
export const QUANT_TIERS = ['small', 'balanced', 'large', 'full'] as const;
export type QuantTier = (typeof QUANT_TIERS)[number];

export interface ModelSource {
  provider: ProviderId;
  /** e.g. "ggerganov/whisper.cpp" or "Qwen/Qwen3-4B-GGUF". */
  repo: string;
  /** Pinned upstream revision. Pinning is what makes sha256 stable over time. */
  revision: string;
}

/**
 * One installable model variant. "Model" and "quantization" are two UI levels but one
 * registry entity: `whisper-large-v3-turbo` at `q5_0` is a distinct entry from the same
 * model at `q8_0`, because they have different digests, sizes and requirements.
 * The catalog groups them by `groupId` for display.
 */
export interface ModelEntry {
  schemaVersion: 1;
  /** Stable unique id, e.g. "asr/whisper-large-v3-turbo-q5_0". */
  id: string;
  /** Groups quantization variants of the same logical model, e.g. "asr/whisper-large-v3-turbo". */
  groupId: string;
  role: ModelRole;
  /** e.g. "whisper", "qwen3", "gemma3". */
  family: string;
  /** Model architecture as reported by the file format, e.g. "whisper", "qwen3". */
  arch: string;
  format: ModelFormat;
  /** ADR-004 gap ①. */
  quantization: Quantization;
  quantTier: QuantTier;

  displayName: string;
  displayNameZh: string;
  descriptionZh: string;
  descriptionEn: string;

  /** BCP-47-ish codes, or "multi" for multilingual. */
  languages: string[];
  /** Free-form catalog tags, e.g. ["recommended-default", "multilingual"]. */
  tags: string[];

  /**
   * Languages for which this model is NOT recommended (ADR-011 decision 1).
   *
   * Not a capability flag — the model still runs. It records that we have MEASURED the
   * output to be unacceptable for that language. For Whisper `base` on Chinese, the
   * errors are not "slightly worse", they are wrong words:
   *   维基百科 → 危机摆科, 华尔街日报 → 花耳街日报, 谷歌 → 古歌,
   *   迈克尔杰克逊逝世 → 麦克尔结克训试事
   * (`Zh-Twitter.ogg`, 337 s; `large-v3-turbo-q5_0` gets all of these right.)
   *
   * The UI filters these out BY DEFAULT when the audio/UI language matches, and says why.
   * It must remain possible to unhide them: `base` is still a sensible choice for English
   * on a weak machine, so removing the model outright would be an over-correction.
   * The problem is the default, not the capability.
   */
  notRecommendedFor?: string[];

  files: ArtifactFile[];
  /** Sum of non-optional file sizes, in bytes. */
  totalSizeBytes: number;

  /** ADR-004 gap ②. Generated by scripts/gen-manifest.mjs, never hand-typed. */
  requirements: ResourceRequirements;
  /** Present for GGUF models; the source of the KV-cache term in `requirements`. */
  gguf?: GgufMetadata;

  /**
   * Known capability trade-offs, shown verbatim in the UI (ADR-013 decision 1).
   *
   * Exists because "faster" is never free and the costs are invisible until they bite:
   * Paraformer has no word-level timestamps, writes numbers as Chinese characters, and
   * lower-cases English. A user who picks it for speed and later needs word-level
   * alignment must be able to learn that BEFORE downloading, not after.
   */
  capabilityCaveats?: string[];

  license: LicenseInfo;
  source: ModelSource;

  /**
   * DELIBERATELY ABSENT: `speed` and `quality` integers.
   * memo.ac hardcodes `speed: 6, quality: 2` etc. with no provenance. ADR-004 decision 3
   * bans fabricated numbers project-wide. Accuracy/speed start as null and are filled in
   * only by a real measurement on this machine.
   */
  benchmark: BenchmarkResult | null;

  /**
   * Speed measured by us on a reference machine. Distinct from `benchmark`
   * (= measured on the user's machine). Always labelled as a reference figure in the UI.
   */
  referenceBenchmark?: ReferenceBenchmark | null;

  /** Set by the catalog build, used for staleness display. */
  catalogVersion: string;
}

/** Installed-model record, persisted as `manifests/<role>/<id>.json`. */
export interface InstalledModel {
  schemaVersion: 1;
  id: string;
  groupId: string;
  role: ModelRole;
  displayName: string;
  quantization: Quantization;
  totalSizeBytes: number;
  installedAt: string;
  /** Last time full content hashing succeeded. */
  verifiedAt: string | null;
  integrity: 'ok' | 'unverified' | 'corrupt' | 'missing_files';
  files: InstalledFile[];
  requirements: ResourceRequirements;
  gguf?: GgufMetadata;
  license: LicenseInfo;
  source: ModelSource;
  benchmark: BenchmarkResult | null;
  catalogVersion: string;
}

export interface InstalledFile {
  role: string;
  name: string;
  sha256: string;
  sizeBytes: number;
  /** Absolute path to the by-name hardlink view (the blob lives under blobs/). */
  path: string;
}

export const CATALOG_SOURCES = ['remote', 'cache', 'bundled'] as const;
export type CatalogSource = (typeof CATALOG_SOURCES)[number];

/** A model plus its quantization variants, as served to the UI. */
export interface CatalogGroup {
  groupId: string;
  role: ModelRole;
  family: string;
  displayName: string;
  displayNameZh: string;
  descriptionZh: string;
  descriptionEn: string;
  languages: string[];
  tags: string[];
  license: LicenseInfo;
  variants: ModelEntry[];
}
